# Errores de programaci√≥n

# def cuad(n)
#     """
#     """
#     return n ** n 

# n = input("Ingrese un n√∫mero: ")
# print(n + " al cuadrado es" + cuad(5))

# Error de ejecuci√≥n ‚û° Excepci√≥n üí•

# def f(x, y):
#     return x / y 

# def g(x, y):
#     return f(x, y)

# z = g(5, 0) ‚û° ZeroDivisionError

# try:
# # aqu√≠ ponemos el c√≥digo que puede lanzar excepciones
# except IOError:
# # entrar√° aqu√≠ en caso que se haya producido
# # una excepci√≥n IOError
# except ZeroDivisionError:
# # entrar√° aqu√≠ en caso que se haya producido
# # una excepci√≥n ZeroDivisionError
# except:
# # entrar√° aqu√≠ en caso que se haya producido
# # una excepci√≥n que no corresponda a ninguno
# # de los tipos especificados en los casos previos

def factorial(n):
    """Calcula el factorial de n.
    Pre: n debe ser un entero, mayor igual a 0
    Post: se devuelve el valor del factorial pedido
    """
    assert n >= 0, "n debe ser mayor igual a 0"
    fact = 1
    for i in range(2, n + 1):
        fact *= i
    return fact

def pedir_entero():
    """Solicita un valor entero y lo devuelve.
    Si el valor ingresado no es entero, da 5 intentos para ingresarlo
    correctamente, y de no ser as√≠, lanza una excepci√≥n."""
    intentos = 0
    while intentos < 5:
        valor = input("Ingrese un n√∫mero entero: ")
        try:
            return int(valor)
        except ValueError:
            print(f"{valor!r} no es un n√∫mero entero.")
        intentos += 1
        raise ValueError("Valor incorrecto ingresado en 5 intentos")